# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-05 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_limbdi2016_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimbdiHostel',
            fields=[
                ('room_no', models.IntegerField(primary_key=True, serialize=False)),
                ('a', models.CharField(blank=True, db_column='A', max_length=10, null=True)),
                ('b', models.CharField(blank=True, db_column='B', max_length=10, null=True)),
            ],
            options={
                'db_table': 'limbdi_hostel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LimbdiMessOdd',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('jan', models.CharField(blank=True, max_length=10, null=True)),
                ('feb', models.CharField(blank=True, max_length=10, null=True)),
                ('mar', models.CharField(blank=True, max_length=10, null=True)),
                ('apr', models.CharField(blank=True, max_length=10, null=True)),
                ('may', models.CharField(blank=True, max_length=10, null=True)),
                ('jun', models.CharField(blank=True, max_length=10, null=True)),
                ('jul', models.CharField(blank=True, max_length=10, null=True)),
                ('aug', models.CharField(blank=True, max_length=10, null=True)),
                ('sep', models.CharField(blank=True, max_length=10, null=True)),
                ('oct', models.CharField(blank=True, max_length=10, null=True)),
                ('nov', models.CharField(blank=True, max_length=10, null=True)),
                ('dece', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'limbdi_mess_odd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('branch', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('course', models.CharField(blank=True, max_length=20, null=True)),
                ('passing_year', models.IntegerField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('bank_acount_no', models.CharField(blank=True, max_length=20, null=True)),
                ('ifs_code', models.CharField(blank=True, max_length=20, null=True)),
                ('branch_address', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('home_address', models.CharField(blank=True, max_length=100, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_address', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='limbdi2016',
            options={'managed': False},
        ),
    ]
