# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-07 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DhanrajHostel',
            fields=[
                ('room_no', models.IntegerField(primary_key=True, serialize=False)),
                ('a', models.CharField(blank=True, db_column='A', max_length=10, null=True)),
                ('b', models.CharField(blank=True, db_column='B', max_length=10, null=True)),
            ],
            options={
                'db_table': 'dhanraj_hoatel',
                'managed': False,
            },
        ),
    ]
