# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-07 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dhanrajhostel',
            table='dhanraj_hostel',
        ),
    ]
